import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css'
import {unstable_setRequestLocale} from 'next-intl/server';
import Navigation from '@/components/navigation'
import { locales } from '@/config';
import { ReactNode } from 'react';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
type Props ={
  children: ReactNode,
  params: {locale:string}
}
export default function LocaleLayout({children, params}:Props) {

  unstable_setRequestLocale(params.locale);
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <Navigation/>
        {children}</body>
    </html>
  )
}

  export function generateStaticParams() {
    return locales.map((locale) => ({locale}));
  }
